[project]
name = "chnu.data-science"
version = "0.1.0"
description = "Data Science course labs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
]
